# Generated by Django 4.2.10 on 2024-03-03 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marriageapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='accounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=15)),
                ('rpassword', models.CharField(max_length=15)),
                ('date', models.DateField()),
            ],
        ),
    ]
