# Generated by Django 4.2.10 on 2024-03-03 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marriageapp', '0002_accounts'),
    ]

    operations = [
        migrations.DeleteModel(
            name='accounts',
        ),
    ]
