# Generated by Django 4.2.10 on 2024-03-04 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marriageapp', '0003_delete_accounts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='responses',
            old_name='name',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='responses',
            name='email',
        ),
    ]
