# Generated by Django 4.2.10 on 2024-03-04 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marriageapp', '0004_rename_name_responses_username_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookingss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=50)),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('cnic', models.CharField(max_length=50)),
                ('events', models.CharField(max_length=50)),
                ('amount', models.CharField(max_length=50)),
                ('date', models.DateField()),
            ],
        ),
    ]
